substitutions:
    _IMAGE_NAME: ofmanager
steps:
    -   name: 'ubuntu'
        entrypoint: 'bash'
        args:
            - ./mvnw
            - package
            - -Pprod
            - -DskipTests
            - jib:build
            - -Dimage=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}
