substitutions:
    _IMAGE_NAME: ofmanager
steps:
    -   name: gcr.io/cloud-builders/java
        args:
            - ./mvnw
            - package
            - -Pprod
            - -DskipTests
            - jib:build
            - -Dimage=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}
